import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { readStyleEntry } from "./helpers/style_source.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceEntry = readFileSync(join(ROOT, "js", "workspace.js"), "utf8");
const workspaceLibrary = readFileSync(join(ROOT, "js", "workspace", "library.js"), "utf8");
const workspaceGroupNavigation = readFileSync(join(ROOT, "js", "workspace", "group_navigation.js"), "utf8");
const workspace = [
	"workspace.js",
	"workspace/dashboard_bindings.js",
	"workspace/dashboard_presets.js",
	"workspace/dashboard_view.js",
	"workspace/component_note.js",
	"workspace/dialogs.js",
	"workspace/group_navigation.js",
	"workspace/library.js",
	"workspace/dom_utils.js",
	"workspace/graph_signature.js",
	"workspace/labels.js",
	"workspace/numeric_range.js",
	"workspace/dashboard_scroll.js",
	"workspace/dashboard_source_groups.js",
	"workspace/sidebar_preferences.js",
].map((path) => readFileSync(join(ROOT, "js", ...path.split("/")), "utf8")).join("\n");
const selector = readFileSync(join(ROOT, "js", "prompt_selector.js"), "utf8");
const providers = readFileSync(join(ROOT, "js", "lib", "control_providers.js"), "utf8");
const widgetAdapters = readFileSync(join(ROOT, "js", "lib", "widget_control_adapters.js"), "utf8");
const nodeControlMenu = readFileSync(join(ROOT, "js", "lib", "node_control_menu.js"), "utf8");
const workspaceControls = readFileSync(join(ROOT, "js", "lib", "workspace_controls.js"), "utf8");
const imageCompareControl = readFileSync(join(ROOT, "js", "lib", "controls", "image_compare.js"), "utf8");
const numericControl = readFileSync(join(ROOT, "js", "lib", "controls", "numeric.js"), "utf8");
const choiceControl = readFileSync(join(ROOT, "js", "lib", "controls", "choice.js"), "utf8");
const booleanControl = readFileSync(join(ROOT, "js", "lib", "controls", "boolean.js"), "utf8");
const taglistControl = readFileSync(join(ROOT, "js", "lib", "controls", "taglist.js"), "utf8");
const textControl = readFileSync(join(ROOT, "js", "lib", "controls", "text.js"), "utf8");
const imageChoiceControl = readFileSync(join(ROOT, "js", "lib", "controls", "image_choice.js"), "utf8");
const markdownControl = readFileSync(join(ROOT, "js", "lib", "controls", "markdown.js"), "utf8");
const nativeOutputControls = readFileSync(join(ROOT, "js", "lib", "native_output_controls.js"), "utf8");
const imageOutputControl = readFileSync(join(ROOT, "js", "lib", "controls", "image_output.js"), "utf8");
const textOutputControl = readFileSync(join(ROOT, "js", "lib", "controls", "text_output.js"), "utf8");
const comfyControls = readFileSync(join(ROOT, "js", "lib", "controls", "comfy.js"), "utf8");
const quickGroupControl = readFileSync(join(ROOT, "js", "lib", "controls", "quick_group_manager.js"), "utf8");
const runtime = readFileSync(join(ROOT, "js", "lib", "quick_group_manager_runtime.js"), "utf8");
const controlRegistry = readFileSync(join(ROOT, "js", "lib", "controls", "registry.js"), "utf8");
const components = readFileSync(join(ROOT, "js", "lib", "workspace_components.js"), "utf8");
const uiSource = ["ui.js", "ui/primitives.js", "ui/transient_surfaces.js", "ui/overlays.js", "ui/controls.js"]
	.map((path) => readFileSync(join(ROOT, "js", "lib", ...path.split("/")), "utf8")).join("\n");
const dashboardModel = readFileSync(join(ROOT, "js", "lib", "dashboard_model.js"), "utf8");
const dashboardComponents = readFileSync(join(ROOT, "js", "lib", "dashboard_components.js"), "utf8");
const dashboardInteractions = readFileSync(join(ROOT, "js", "lib", "dashboard_interactions.js"), "utf8");
const dashboardCommands = readFileSync(join(ROOT, "js", "lib", "dashboard_commands.js"), "utf8");
const dashboardLayout = readFileSync(join(ROOT, "js", "lib", "dashboard_layout.js"), "utf8");
const dashboardSizing = readFileSync(join(ROOT, "js", "lib", "dashboard_sizing.js"), "utf8");
const dashboardSelection = readFileSync(join(ROOT, "js", "lib", "dashboard_selection.js"), "utf8");
const dashboardPresets = readFileSync(join(ROOT, "js", "lib", "dashboard_presets.js"), "utf8");
const dashboardPresetRuntime = readFileSync(join(ROOT, "js", "lib", "dashboard_preset_runtime.js"), "utf8");
const markdownEditor = readFileSync(join(ROOT, "js", "lib", "markdown_editor.js"), "utf8");
const groupNavigation = readFileSync(join(ROOT, "js", "lib", "group_navigation.js"), "utf8");
const groupNavigationModel = readFileSync(join(ROOT, "js", "lib", "group_navigation_model.js"), "utf8");
const libraryStore = readFileSync(join(ROOT, "js", "lib", "library_store.js"), "utf8");
const imagePreview = readFileSync(join(ROOT, "js", "lib", "image_preview.js"), "utf8");
const imageAssetControl = readFileSync(join(ROOT, "js", "lib", "image_asset_control.js"), "utf8");
const imageAssets = readFileSync(join(ROOT, "js", "lib", "image_assets.js"), "utf8");
const promptEntryDetails = readFileSync(join(ROOT, "js", "lib", "prompt_entry_details.js"), "utf8");
const categoryColor = readFileSync(join(ROOT, "js", "lib", "category_color.js"), "utf8");
const ui = uiSource;
const uiStyles = readFileSync(join(ROOT, "js", "lib", "ui.css"), "utf8");
const theme = readStyleEntry(new URL("../js/lib/theme.css", import.meta.url));
const themeLibrary = readFileSync(join(ROOT, "js", "lib", "theme-library.css"), "utf8");
const workspaceIcon = readFileSync(join(ROOT, "js", "assets", "aaalice-workspace.svg"), "utf8");
const enLocale = readFileSync(join(ROOT, "locales", "en", "main.json"), "utf8");
const zhLocale = readFileSync(join(ROOT, "locales", "zh", "main.json"), "utf8");


test("workspace uses event-driven refresh without polling", () => {
	assert.match(workspace, /addEventListener\("graphChanged"/);
	assert.match(workspace, /requestAnimationFrame/);
	assert.doesNotMatch(workspace, /setInterval/);
});

test("dashboard and library searches share a collapsible event-driven control", () => {
	assert.match(components, /export function createCollapsibleSearch/);
	assert.match(components, /searchToggleButton\(\{ label, value, open, disabled/);
	assert.match(components, /input\.className = "aa-ui-search-input"/);
	assert.match(components, /iconName: "arrowRight"[^}]*className: "aa-ui-search-collapse"/);
	assert.match(uiSource, /export function searchToggleButton/);
	assert.doesNotMatch(uiSource, /searchApplied/);
	assert.match(uiSource, /control\.replaceChildren\(icon\("search"\)\)/);
	assert.match(uiSource, /className: "aa-ui-search-summary__query"/);
	assert.match(uiSource, /control\.setAttribute\("aria-expanded"/);
	assert.match(components, /event\.key === "Escape"/);
	assert.match(components, /queueMicrotask/);
	assert.match(workspace, /workspaceViewState = \{/);
	assert.match(workspace, /dashboard: \{ query: "", searchOpen: false, focusSearch: false, focusHost: null, selectedItemIds: new Set\(\)/);
	assert.match(workspace, /viewState\.searchOpen = open; viewState\.focusSearch = open/);
	assert.doesNotMatch(workspace, /if \(!open\) viewState\.query = ""/);
	assert.doesNotMatch(workspace, /container\._aaalice(?:Dashboard|Library)(?:Query|SearchOpen|SearchShouldFocus)/);
	assert.match(workspace, /disabled: !page \|\| editMode/);
	assert.match(workspace, /item\.dataset\.searchText/);
	assert.match(workspace, /applyDashboardSearch\(value\)/);
	assert.match(workspace, /library: \{ query: "", searchOpen: false, focusSearch: false/);
	assert.match(workspace, /onInput: \(value\) => \{ query = value; viewState\.query = value; drawEntries\(\)/);
	assert.match(theme, /\.aa-workspace-search \{/);
	assert.match(workspace, /createWorkspaceToolbar\(\[\], \{ className: `aa-dashboard-toolbar/);
	assert.doesNotMatch(workspace, /container\.append\(toolbar, \.\.\.\(search\.panel/);
	assert.match(theme, /\.aa-dashboard-toolbar\.is-searching, \.aa-library-toolbar\.is-searching/);
	assert.match(theme, /@keyframes aa-workspace-search-open/);
});

test("dashboard search mounts live controls for every page and excludes group context", () => {
	assert.match(dashboardComponents, /export function createDashboardSearchResults/);
	assert.match(dashboardComponents, /renderItem\?\.\(entry\)/);
	assert.match(workspace, /const searchResultPages = searchOpen \? model\.pages\.map/);
	assert.match(workspace, /targetPage\.items\.filter\(\(item\) => item\.kind === "control"\)/);
	assert.match(workspace, /searchText: normalizeDashboardSearchText\(title\)/);
	assert.match(workspace, /renderItem: \(entry\) => renderControlCard\(entry\.item, entry\.page, entry\.controls, \{ search: true \}\)/);
	assert.doesNotMatch(workspace, /groupName\.toLocaleLowerCase\(\)\.includes\(needle\)/);
	assert.match(workspace, /matchesDashboardSearch\(item\.dataset\.searchText \|\| "", needle\)/);
	assert.match(workspace, /searchResults\.updateSummary\?\.\(\{ count: visibleItems, query: needle \}\)/);
	assert.doesNotMatch(workspace, /viewState\.searchTarget/);
	assert.doesNotMatch(workspace, /target\.scrollIntoView\(\{ block: "center", behavior: "smooth" \}\)/);
});

test("workspace composition root owns one view-state source for every sidebar view", () => {
	assert.match(workspaceEntry, /library: \{ query: "", searchOpen: false, focusSearch: false, focusHost: null/);
	assert.match(workspaceEntry, /groups: \{ query: "", searchOpen: false, focusSearch: false, focusHost: null \}/);
	assert.match(workspaceEntry, /configureLibraryWorkspace\(\{[^}]*viewState: workspaceViewState\.library/);
	assert.match(workspaceEntry, /configureGroupNavigation\(\{[\s\S]*?viewState: workspaceViewState\.groups/);
	assert.match(workspaceEntry, /for \(const viewState of Object\.values\(workspaceViewState\)\) if \(viewState\.focusHost === element\)/);
	assert.match(workspaceLibrary, /const viewState = runtime\.viewState/);
	assert.match(workspaceGroupNavigation, /const viewState = runtime\.viewState/);
	assert.doesNotMatch(workspaceLibrary, /const viewState = \{ query:/);
	assert.doesNotMatch(workspaceGroupNavigation, /const viewState = \{ query:/);
});

test("PromptSelector can open the official sidebar directly on library management", () => {
	assert.match(workspace, /export function openWorkspace/);
	assert.match(workspace, /sidebar\.activeSidebarTabId = TAB_ID/);
	assert.match(workspace, /activeWorkspace = view/);
	assert.doesNotMatch(selector, /querySelector\([^\n]*sidebar|\.click\(\)/);
	assert.match(workspace, /export async function openPromptLibraryEntryEditor\(entryId\)/);
	assert.match(workspace, /snapshot\.entries\.find\(\(item\) => item\.id === entryId\)/);
	assert.match(workspace, /openLibraryEntryEditor\(entry\)/);
	assert.match(selector, /openPromptLibraryEntryEditor\(entry\.id\)/);
	assert.match(selector, /preview\.addEventListener\("dblclick"/);
	assert.match(selector, /thumbnailEditHint/);
	assert.match(selector, /copy\.addEventListener\("click", \(\) => mutate/);
	assert.match(selector, /"aria-pressed": String\(isSelected\)/);
	assert.match(selector, /className: "aa-prompt-selector-edit"/);
	assert.match(selector, /className: `aa-prompt-selector-favorite\$\{isFavorite \? " is-active" : ""\}`/);
	assert.match(selector, /openFavoritePicker\(entry\)/);
	assert.match(selector, /updateEntry\(entry\.id, \{ collectionIds: \[\] \}\)/);
	assert.match(selector, /addCollectionId: target\.value/);
	assert.match(selector, /className: "aa-prompt-selector-row-actions"/);
	assert.match(selector, /event\.preventDefault\(\); event\.stopPropagation\(\); closePromptSurfaces\(node\)/);
	assert.match(theme, /\.aa-prompt-selector-row:hover \.aa-prompt-selector-row-actions \.aa-ui-button/);
	assert.match(theme, /\.aa-prompt-selector-edit \{ color: var\(--aa-ui-accent\); \}/);
	assert.match(theme, /\.aa-prompt-selector-favorite \{[^}]*color: var\(--aa-ui-warning\);/);
	assert.match(theme, /\.aa-prompt-selector-favorite\.is-active \{[^}]*background: transparent;[^}]*box-shadow: none;/);
	assert.match(theme, /\.aa-prompt-selector-favorite\.is-active \.aa-ui-icon \{ fill: currentColor; \}/);
});

test("resolution bindings keep the sidebar card compact while preserving canvas editing", () => {
	assert.match(workspaceEntry, /resolved\.kind === "resolution"/);
	assert.match(workspaceEntry, /item\.layout\.rowSpan === 40/);
	assert.match(workspaceEntry, /layoutProjection: \{ \.\.\.\(resolved\.layoutProjection \|\| \{\}\), rowSpan: DASHBOARD_DEFAULT_CONTROL_ROW_SPAN \}/);
	assert.match(theme, /\.aa-control-card\[data-control-kind="resolution"\]/);
	assert.match(theme, /\.aa-control-resolution\.aa-resolution-sidebar-control/);
});

test("workspace visual hierarchy uses a compact shell, dedicated icon and heading page menu", () => {
	assert.match(workspace, /icon: "aaalice-workspace-sidebar-icon"/);
	assert.match(workspace, /element\.classList\.add\("aa-workspace-host"\)/);
	assert.match(theme, /\.aa-workspace-host \{[^}]*height: 100%;[^}]*min-height: 0;[^}]*overflow: hidden;/);
	assert.match(theme, /\.aa-workspace \{[^}]*flex: 1;/);
	assert.match(theme, /\.aaalice-workspace-sidebar-icon[\s\S]*mask: url\("\.\.\/assets\/aaalice-workspace\.svg"\)/);
	assert.match(workspaceIcon, /viewBox="0 0 24 24"/);
	assert.match(workspaceIcon, /stroke-linecap="round"/);
	assert.doesNotMatch(workspaceIcon, /<circle/);
	assert.match(components, /export function createPageRail/);
	assert.match(components, /aa-dashboard-page-dot__marker/);
	assert.match(components, /aa-dashboard-page-rail__hover-area/);
	assert.match(components, /root\.append\(hoverArea, list\)/);
	assert.doesNotMatch(components, /aa-dashboard-page-cursor|positionCursor|cursorFrame|ResizeObserver/);
	assert.match(components, /let collapseFrame = 0/);
	assert.match(components, /const isInteractiveSurfaceHovered = \(\) => hoverArea\.matches\(":hover"\) \|\| list\.matches\(":hover"\)/);
	assert.match(components, /hoverArea\.addEventListener\("pointerenter", keepExpanded\)/);
	assert.match(components, /list\.addEventListener\("pointerenter", keepExpanded\)/);
	assert.doesNotMatch(components, /root\.addEventListener\("pointerenter", keepExpanded\)/);
	assert.match(components, /collapseFrame = requestAnimationFrame/);
	assert.match(components, /aa-dashboard-page-dot/);
	assert.doesNotMatch(components, /root\.addEventListener\("wheel"/);
	assert.doesNotMatch(components, /wheelDistance|wheelDirection|wheelResetTimer|resetWheel/);
	assert.match(components, /Collapse after layout settles/);
	assert.match(components, /root\.addEventListener\("pointerleave", scheduleCollapse\)/);
	assert.match(components, /root\.destroy = cancelCollapse/);
	assert.match(components, /root\.addEventListener\("focusin"/);
	assert.match(components, /root\.addEventListener\("focusout"/);
	assert.match(components, /PAGE_RAIL_COLLAPSED_GAP = 4/);
	assert.match(components, /PAGE_RAIL_EXPANDED_GAP = 10/);
	assert.match(components, /state\.expanded \? PAGE_RAIL_EXPANDED_GAP : PAGE_RAIL_COLLAPSED_GAP/);
	assert.doesNotMatch(components, /const activeIndex = \(\)|updateExpansionOffset|aa-dashboard-page-rail-active-shift/);
	assert.match(components, /const setExpanded = \(expanded\) =>/);
	assert.match(components, /const keepExpanded = \(\) =>/);
	assert.doesNotMatch(components, /expansionAnchorId|reanchor|requestedAnchorId/);
	assert.match(components, /updateHoverHeight\(\);/);
	assert.doesNotMatch(components, /event\.propertyName === "gap"|event\.propertyName === "transform"/);
	assert.match(components, /state\.onSelect\?\.\(next\.id\)/);
	assert.match(theme, /\.aa-dashboard-body \{[^}]*height: 0;[^}]*flex: 1 1 0;[^}]*grid-template-columns: minmax\(0, 1fr\) 38px;[^}]*grid-template-rows: minmax\(0, 1fr\);/);
	assert.match(theme, /\.aa-dashboard-page-rail \{[^}]*position: relative;[^}]*height: auto;[^}]*min-height: 0;[^}]*grid-column: 2;[^}]*grid-row: 1;/);
	assert.match(theme, /\.aa-dashboard-page-list \{[^}]*position: absolute;[^}]*top: 50%;[^}]*right: 7px;[^}]*bottom: auto;[^}]*left: 0;[^}]*box-sizing: border-box;[^}]*gap: 2px;[^}]*transform: translateY\(-50%\);[^}]*transition: gap/);
	assert.match(theme, /\.aa-dashboard-page-rail\.is-expanded \.aa-dashboard-page-list[\s\S]*?gap: 10px;/);
	assert.match(theme, /\.aa-dashboard-page-rail__hover-area \{[^}]*top: 50%;[^}]*max-height: calc\(100% - 24px\);[^}]*pointer-events: auto;[^}]*transform: translateY\(-50%\);/);
	assert.match(theme, /\.aa-dashboard-page-list \{[^}]*transition: gap \.18s/);
	assert.doesNotMatch(theme, /aa-dashboard-page-rail-active-shift|\.aa-dashboard-page-list \{[^}]*translate3d/);
	assert.match(components, /const hitHeight = Math\.max\(56, clusterHeight\)/);
	assert.match(components, /list\.style\.height = `\$\{hitHeight\}px`/);
	assert.doesNotMatch(theme, /\.aa-dashboard-page-rail \{[^}]*position: absolute/);
	assert.doesNotMatch(theme, /\.aa-dashboard-page-cursor/);
	assert.match(theme, /\.aa-dashboard-page-dot/);
	assert.match(theme, /\.aa-dashboard-page-rail:has\(\.aa-dashboard-page-dot:focus-visible\)/);
	assert.doesNotMatch(theme, /\.aa-dashboard-page-rail:focus-within/);
	assert.match(theme, /\.aa-dashboard-page-rail\.is-expanded \.aa-dashboard-page-dot/);
	assert.match(theme, /\.aa-dashboard-page-dot \.aa-ui-button__label/);
	assert.match(theme, /\.aa-dashboard-page-rail\.is-expanded \.aa-dashboard-page-dot\.is-active[\s\S]*?box-shadow: [^;]*color-mix/);
	assert.match(components, /aa-dashboard-page-menu__row/);
	assert.match(components, /aria-haspopup": "dialog"/);
	assert.match(components, /createAnchoredPopover\(\{[\s\S]*?aa-dashboard-page-popover/);
	assert.match(components, /application\/x-aaalice-page/);
	assert.match(components, /children: \[\s*el\("span", \{ className: "aa-dashboard-page-menu__drag-handle"[\s\S]*?el\("span", "aa-dashboard-page-menu__index"/);
	assert.doesNotMatch(components, /\.\.\.\(editMode \? \[el\("span", \{ className: "aa-dashboard-page-menu__drag-handle"/);
	assert.match(components, /clearDropTargets/);
	assert.match(components, /onReorderPage\?\.\(entry\.id, target\.id\)/);
	assert.match(workspace, /onSelectPage: selectPage/);
	assert.match(workspace, /onReorderPage: reorderPage/);
	assert.match(workspace, /try \{ resolved = resolveControlBindingSet\(item, resolve\); \}/);
	assert.match(workspace, /flushActiveDashboardPresetOnSave\(\)/);
	assert.doesNotMatch(workspace, /const currentIndex = model\.pages\.findIndex/);
	assert.doesNotMatch(workspace, /model\.pages\[currentIndex \+ direction\]/);
	assert.doesNotMatch(workspace, /source: "boundary"/);
	assert.match(components, /aria-current/);
	assert.match(components, /ArrowUp/);
	assert.doesNotMatch(components, /if \(!editMode \|\| !event\.altKey/);
	assert.doesNotMatch(components, /aa-workspace-brand/);
	assert.match(components, /ariaLabel: title/);
	assert.match(components, /root\.dataset\.workspace = activeTab/);
	assert.match(components, /root\.dataset\.workspace = value/);
	assert.match(workspace, /className: "aa-dashboard-edit-toggle"/);
	assert.match(workspace, /variant: "ghost"/);
	assert.match(workspace, /active: editMode/);
	assert.match(theme, /\.aa-dashboard-edit-toggle\.aa-ui-button\.is-active/);
	assert.match(theme, /\.aa-workspace\[data-workspace="library"\] \{[^}]*--aa-ui-accent: var\(--aa-workspace-library-accent\)/);
	assert.match(theme, /--aa-ui-accent-soft: color-mix/);
	assert.match(theme, /--aa-ui-focus: var\(--aa-workspace-library-accent\)/);
	assert.match(theme, /\.aa-workspace-tabs\[data-value="library"\]/);
	assert.match(theme, /\.aa-workspace-tabs \{[^}]*display: grid;[^}]*overflow: hidden;/);
	assert.match(theme, /transform \.2s cubic-bezier/);
	assert.match(workspace, /onTabChange: \(value\) => \{ activeWorkspace = value; scheduleStructuralRender\(\); \}/);
	assert.doesNotMatch(components, /aa-control-card-indicator/);
	assert.match(theme, /\.aa-dashboard-page-menu__row\.is-active/);
	assert.match(theme, /\.aa-dashboard-page-menu__index/);
	assert.match(theme, /\.aa-dashboard-page-menu__name/);
	assert.match(theme, /\.aa-dashboard-page-menu__drag-handle/);
	assert.match(theme, /\.aa-dashboard-page-menu__row\.is-drop-target/);
	assert.match(theme, /margin-right: auto/);
	assert.match(theme, /backdrop-filter: blur\(12px\)/);
	assert.doesNotMatch(workspace, /initialEdge/);
	assert.match(workspace, /aa-dashboard-scroll\$\{pageTransitionClass\}/);
	assert.doesNotMatch(dashboardInteractions, /PAGE_WHEEL_PAGE_INTERVAL/);
	assert.doesNotMatch(dashboardInteractions, /nextPageAt/);
	assert.doesNotMatch(dashboardInteractions, /pageInterval/);
	assert.doesNotMatch(dashboardInteractions, /pendingSteps|awaitingPageId|hasLegacyWheelDetent|wheelDeltaY \?\? event\.wheelDelta|gestureConsumed|lastWheelAt/);
	assert.doesNotMatch(dashboardInteractions, /bindDashboardBoundaryPaging/);
	assert.doesNotMatch(dashboardInteractions, /cancelDashboardBoundaryPaging/);
	assert.doesNotMatch(dashboardInteractions, /destroyDashboardBoundaryPaging/);
	assert.doesNotMatch(dashboardInteractions, /hasScrollableDescendant/);
	assert.doesNotMatch(dashboardInteractions, /clearPostScrollCheck/);
	assert.doesNotMatch(dashboardInteractions, /eventTarget\.isConnected/);
	assert.doesNotMatch(dashboardInteractions, /event\.defaultPrevented/);
	assert.doesNotMatch(dashboardInteractions, /addEventListener\(["']scroll/);
	assert.doesNotMatch(workspace, /bindDashboardBoundaryPaging/);
	assert.doesNotMatch(workspace, /scroller: scroll/);
	assert.doesNotMatch(workspace, /pageId: page\.id/);
	assert.match(workspace, /dashboardPageRails = new WeakMap/);
	assert.doesNotMatch(workspace, /boundaryPagingState/);
	assert.match(workspace, /destroyDashboardPageRailForRoot/);
	assert.doesNotMatch(workspace, /container\.addEventListener\("pointerdown"/);
	assert.match(workspace, /beforeConfigureGraph\(\) \{ clearGroupNavigationCanvasPointer\(\); closeGroupNavigationWheel\(\); closeWorkspaceDialogs\(\); workspaceViewState\.dashboard\.pageTransition = null; resetDashboardScrollStates\(\); invalidateCanvasControlBindingResolution\(\); \}/);
	assert.doesNotMatch(workspace, /beforeConfigureGraph\(\)[\s\S]{0,220}queueMicrotask/);
	assert.doesNotMatch(workspace, /isEnabled: \(\) => activeWorkspace === "dashboard"/);
	assert.doesNotMatch(workspace, /requestPage: \(direction\) =>/);
	assert.doesNotMatch(workspace, /onAdvance: \(\) => selectPage\(model\.pages\[activePageIndex/);
	assert.doesNotMatch(workspace, /onRetreat: \(\) => selectPage\(model\.pages\[activePageIndex/);
	assert.match(workspace, /destroy: destroyWorkspaceSidebar/);
	assert.match(workspace, /workspaceOwnedTrees = new WeakMap/);
	assert.match(workspace, /workspaceOwnershipObservers = new Map/);
	assert.match(workspace, /workspaceParentObservers = new Map/);
	assert.match(workspace, /root\.childElementCount === 1 && root\.firstElementChild === ownedTree/);
	assert.match(workspace, /root\.checkVisibility && !root\.checkVisibility\(\)/);
	assert.match(workspace, /else if \(isWorkspaceRootInteractive\(root\)\) renderWorkspace\(root\)/);
	assert.match(workspace, /if \(!interactive\) \{ wasInteractive = false; suspendWorkspaceRoot\(element\); return; \}/);
	assert.match(workspace, /if \(!wasInteractive\) \{ wasInteractive = true; lastColumnBucket = next; scheduleRender\(\)/);
	assert.match(workspace, /focusHost === host && isWorkspaceRootInteractive\(host\)/);
	assert.match(workspace, /workspacePinTooltips = new WeakMap\(\)/);
	assert.doesNotMatch(workspace, /mounted\.delete\(element\);\s*workspacePinTooltip\.hide\(\)/);
	assert.match(workspace, /ownershipObserver\.observe\(element, \{ childList: true \}\)/);
	assert.match(workspace, /parentObserver\.observe\(element\.parentElement, \{ childList: true \}\)/);
	assert.match(workspace, /captureDashboardPageSnapshot/);
	assert.match(workspace, /captureDashboardPageSnapshots/);
	assert.match(workspace, /pageTransition\?\.snapshots\?\.get\(host\)/);
	assert.match(workspace, /snapshotField\.type !== "file"/);
	assert.doesNotMatch(workspace, /onReorderStart/);
	assert.match(components, /onReorderStart/);
	assert.doesNotMatch(workspace, /detail\.source !== "boundary"/);
	assert.match(workspace, /activeWorkspace = value; scheduleStructuralRender\(\)/);
	assert.match(workspace, /closeWorkspaceTransientSurfaces\(element\);/);
	assert.match(workspace, /closeWorkspaceTransientSurfaces\(ownedTree\)/);
	assert.match(workspace, /function suspendWorkspaceRoot\(element\)/);
	assert.match(workspace, /destroySharedControls\(ownedTree\)/);
	assert.match(ui, /export function closeAnchoredPopoversWithin/);
	assert.match(ui, /export function hasAnchoredPopoverWithin/);
	assert.match(ui, /export function closeContextMenuWithin/);
	assert.match(ui, /export function hasContextMenuWithin/);
	assert.match(ui, /export function onContextMenuClose/);
	assert.match(ui, /export function closeTooltipWithin/);
	assert.match(ui, /isOwnedBy: \(container\)/);
	assert.match(workspace, /if \(!interactive\)/);
	assert.match(workspace, /hasAnchoredPopoverWithin\(root\) \|\| hasContextMenuWithin\(root\)/);
	assert.match(workspace, /onContextMenuClose\(flushDeferredWorkspaceRender\)/);
	assert.match(ui, /if \(closed\) return;\s*reposition\(\)/);
	assert.match(workspace, /\.aa-dashboard-scroll:not\(\.is-page-leaving\)/);
	assert.match(workspace, /dashboardScrollPositions = new WeakMap\(\)/);
	assert.match(workspace, /rememberDashboardScroll\(root\);[\s\S]*root\.replaceChildren\(\)/);
	assert.match(workspace, /"data-dashboard-page-id": page\.id/);
	assert.match(workspace, /if \(searchOpen\) scrollState\.searchTop = scroll\.scrollTop/);
	assert.match(workspace, /else scrollState\.pages\.set\(page\.id, scroll\.scrollTop\)/);
	assert.match(workspace, /setScrollTopImmediately\(scroll, searchOpen \? scrollState\.searchTop : dashboardScrollTop\(host, page\.id\)\)/);
	assert.match(workspace, /deleteDashboardScrollState\(element\)/);
	assert.doesNotMatch(workspace, /pageTransition\?\.initialEdge/);
	assert.doesNotMatch(workspace, /scroll\.scrollHeight - scroll\.clientHeight/);
	assert.match(workspace, /if \(previousTransition && id === fromPageId\)/);
	assert.match(workspace, /createPageRail/);
	assert.match(workspace, /children: \[pageStage, pageRail, selectionBar\.root\]/);
	assert.match(workspace, /dashboardColumnsForWorkspaceWidth\(container\.clientWidth\)/);
	assert.match(workspace, /aa-dashboard-page-stage/);
	assert.match(theme, /\.aa-dashboard-page-stage \{[^}]*height: 100%;[^}]*overflow: hidden;[^}]*grid-template: minmax\(0, 1fr\) \/ minmax\(0, 1fr\);/);
	assert.match(theme, /@keyframes aa-dashboard-page-forward-in/);
	assert.match(theme, /@keyframes aa-dashboard-page-forward-out/);
	assert.match(theme, /@keyframes aa-dashboard-page-backward-in/);
	assert.match(theme, /@keyframes aa-dashboard-page-backward-out/);
	assert.match(theme, /\.aa-dashboard-scroll\.is-page-entering-forward \{[^}]*animation:[^;]*\.18s/);
	assert.match(theme, /\.aa-dashboard-scroll\.is-page-leaving \{[^}]*position: absolute;[^}]*inset: 0;[^}]*width: 100%;[^}]*height: 100%;[^}]*box-sizing: border-box;/);
	assert.match(theme, /\.aa-dashboard-scroll\.is-page-leaving-forward \{[^}]*animation:[^;]*\.18s/);
	assert.match(workspace, /setTimeout\(\(\) => pageSnapshot\.remove\(\), 260\)/);
	assert.match(theme, /prefers-reduced-motion: reduce[\s\S]*\.aa-dashboard-scroll\.is-page-entering/);
	assert.match(dashboardLayout, /export function insertEntries/);
	assert.match(dashboardLayout, /entry\.layout = firstRowWithoutOverlap\(entry\.layout, placed\)/);
	assert.match(dashboardCommands, /insertEntries\(page, ordered\.map\(\(item\) => item\.id\), \{ groupId \}\)/);
	assert.match(dashboardCommands, /insertEntry\(page, groupId, \{ row, column \}/);
	assert.match(dashboardCommands, /removeEmptyGroups\(page\); insertEntry\(page, group\.id, group\.layout\)/);
	assert.match(dashboardCommands, /if \(groupId\).*insertEntry\(page, groupId, group\.layout\)/);
	assert.match(dashboardCommands, /export function moveTopLevelSelection/);
	assert.match(dashboardInteractions, /normalizeDragSelection/);
	assert.match(dashboardInteractions, /hit\?\.closest\?\.\("\[data-dashboard-group-id\]"\)/);
	assert.match(dashboardInteractions, /current\.membershipTarget = isGroupMembershipDrop\(target\.groupId, current\.sourceGroupIds\)/);
	assert.match(dashboardInteractions, /aa-dashboard-group-drop-label/);
	assert.match(theme, /\.aa-dashboard-group\.is-drop-target \{[^}]*background:/);
	assert.match(theme, /\.aa-dashboard-group-drop-label \{[^}]*pointer-events: none;/);
	assert.match(workspace, /groupDropLabel: t\("aaalice\.workspace\.group\.addItem", "Add to group"\)/);
	assert.match(workspace, /onDropSelection: \(itemIds, groupIds, target\)/);
});

test("structural sidebar changes bypass focus deferral without weakening value-control protection", () => {
	assert.match(workspaceEntry, /let forcedWorkspaceRender = false/);
	assert.match(workspaceEntry, /function scheduleRender\(view = null, \{ structural = false \} = \{\}\)/);
	assert.match(workspaceEntry, /const forceFocusRender = structural \|\| forcedWorkspaceRender/);
	assert.match(workspaceEntry, /function scheduleStructuralRender\(view = null\)/);
	assert.match(workspaceEntry, /updateDashboard\(callback\)[\s\S]*scheduleStructuralRender\(\)/);
	assert.match(workspaceEntry, /onTabChange: \(value\) => \{ activeWorkspace = value; scheduleStructuralRender\(\); \}/);
	assert.match(workspace, /updateDashboardPresetState\(callback, detail = null, \{ structural = false \}/);
	assert.match(workspace, /applyDashboardPreset[\s\S]*scheduleStructuralRender\("dashboard"\)/);
	assert.match(workspaceLibrary, /aa-library-filter-select[\s\S]*runtime\.scheduleStructuralRender\(\)/);
	assert.match(workspaceGroupNavigation, /runtime\.scheduleStructuralRender\("groups"\)/);
	assert.match(workspaceEntry, /input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\)/);
	assert.match(workspaceEntry, /data-aaalice-value-field="true"/);
	assert.match(workspaceEntry, /document\.querySelector\('\.aa-control-inline-editor'\)/);
	const schedulerStart = workspaceEntry.indexOf("function scheduleRender");
	const frameGuard = workspaceEntry.indexOf("\n\tif (renderFrame) return;", schedulerStart);
	const focusGuard = workspaceEntry.indexOf("\n\tif (hasActiveControlGestures()", schedulerStart);
	assert.ok(frameGuard >= 0 && focusGuard > frameGuard, "a queued structural render must not leave a stale focus-deferred render behind");
	assert.match(workspaceEntry, /function hasWorkspacePopover\(\)[\s\S]*hasAnchoredPopoverWithin/);
	assert.match(workspaceEntry, /focusout[\s\S]*flushDeferredWorkspaceRender/);
});

test("PromptSelector exposes scannable selected and category states", () => {
	assert.match(selector, /aa-prompt-selector-toolbar/);
	assert.match(selector, /aa-prompt-selector-search-toggle/);
	assert.match(selector, /searchToggleButton\(\{ label:[^}]*value: query/);
	assert.match(selector, /iconName: "arrowRight"[^}]*className: "aa-ui-search-collapse"/);
	assert.match(selector, /aa-prompt-selector-search/);
	assert.match(selector, /search\.className = "aa-ui-search-input"/);
	assert.match(selector, /search\.setAttribute\("data-autocomplete-plus", ""\)/);
	assert.match(selector, /search\.hasAttribute\("data-autocomplete-plus-open"\)/);
	assert.match(selector, /queueMicrotask/);
	assert.match(selector, /list\._aaaliceVirtualList\?\.setItems\(filteredEntries\(node, stateFor\(node\)\), \{ preserveScroll: false \}\)/);
	assert.match(selector, /mountPromptEntries/);
	assert.match(selector, /mountVirtualList/);
	assert.match(selector, /root\.append\(toolbar, list, footer\);\s*node\._aaalicePromptSelectorView = view;\s*list\.scrollTop = listScrollTop;\s*virtualList\.refresh\(\);/s);
	assert.match(selector, /createImagePreview/);
	assert.match(imagePreview, /aa-image-preview-selection/);
	assert.match(imagePreview, /icon\("statusCheck"\)/);
	assert.match(selector, /aa-prompt-selector-title/);
	assert.match(selector, /bindPromptEntryDetails\(copy, entry\)/);
	assert.match(promptEntryDetails, /promptDetailsTooltip = createTooltip/);
	assert.match(promptEntryDetails, /PROMPT_DETAILS_HOVER_DELAY = 600/);
	assert.match(selector, /selectionSummaryTooltip = createTooltip/);
	assert.match(selector, /bindSelectionSummary\(categoryFilter\.control/);
	assert.match(selector, /bindSelectionSummary\(summary/);
	assert.match(selector, /categorySelectionSummary/);
	assert.match(selector, /selectedPromptSummary/);
	assert.match(promptEntryDetails, /aa-prompt-entry-details-prompt/);
	assert.match(promptEntryDetails, /collectionItems\(entry\.collections/);
	assert.match(selector, /aa-prompt-selector-summary/);
	assert.match(selector, /aa-prompt-selector-count/);
	assert.match(selector, /_aaalicePromptSelectedOnly/);
	assert.match(selector, /"aria-pressed": String\(selectedOnly\)/);
	assert.match(selector, /entries\.filter\(\(entry\) => selectedIds\.has\(entry\.id\)\)/);
	assert.match(selector, /countPromptSelectionsByCategory/);
	assert.match(selector, /aa-prompt-selector-clear-action/);
	assert.match(selector, /clearAction\.hidden = !state\.selections\.length/);
	assert.match(selector, /mutate\(node, clearPromptSelections\)/);
	assert.match(selector, /aa-prompt-selector-empty/);
	assert.match(selector, /isSelected \? " is-selected"/);
	assert.match(selector, /className: "aa-prompt-selector", attrs: \{ "data-capture-wheel": "true" \}/);
	assert.match(selector, /className: "aa-prompt-selector-list", attrs: \{ tabindex: "0" \}/);
	assert.match(selector, /list\.addEventListener\("pointerenter", \(\) => \{[\s\S]*root\.contains\(active\)[\s\S]*active\.matches\('input, textarea, select, \[contenteditable="true"\]'\)[\s\S]*list\.classList\.add\("is-wheel-capture-focused"\)[\s\S]*list\.focus\(\{ preventScroll: true \}\)/);
	assert.match(selector, /list\.addEventListener\("keydown", clearWheelCaptureFocus\)/);
	assert.match(selector, /list\.addEventListener\("blur", clearWheelCaptureFocus\)/);
	assert.doesNotMatch(selector, /list\.addEventListener\("wheel"/);
	assert.match(theme, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\) 34px 34px/);
	assert.match(theme, /\.aa-prompt-selector-toolbar\.is-searching \{ grid-template-columns: minmax\(0, 1fr\); \}/);
	assert.match(theme, /\.dom-widget:has\(> \.aa-prompt-selector\) \{[^}]*position: relative;[^}]*min-height: 240px;[^}]*overflow: hidden;[^}]*pointer-events: none !important;/);
	assert.match(theme, /\.aa-prompt-selector \{[^}]*position: absolute;[^}]*inset: 0;[^}]*min-height: 0;[^}]*overflow: hidden;/);
	assert.match(theme, /\.lg-node-widgets \.aa-prompt-selector \{[^}]*position: relative;[^}]*inset: auto;[^}]*height: 100%;[^}]*min-height: 240px;/);
	assert.match(theme, /\.aa-prompt-selector-list \{[^}]*min-height: 0;[^}]*overflow: auto;[^}]*outline: none;/);
	assert.match(theme, /\.aa-prompt-selector-list:focus-visible:not\(\.is-wheel-capture-focused\) \{[^}]*box-shadow: inset 3px 0/);
	assert.match(theme, /\.aa-prompt-selector\.is-resizing, \.aa-prompt-selector\.is-resizing \* \{ pointer-events: none !important; \}/);
	assert.match(theme, /\.aa-prompt-selector-row\.is-selected/);
	assert.match(theme, /\.aa-prompt-selector-row \{[^}]*grid-template-columns: 38px minmax\(0, 1fr\);/);
	assert.match(theme, /\.aa-prompt-selector-row-actions \{[^}]*position: absolute;/);
	assert.match(theme, /--aa-prompt-row-surface: var\(--aa-ui-accent-soft\)/);
	assert.match(theme, /linear-gradient\(90deg, transparent, var\(--aa-prompt-row-surface\) 28%\)/);
	assert.doesNotMatch(theme, /aa-prompt-selector-row-actions \{ background:[^}]*aa-ui-surface/);
	assert.match(theme, /\.aa-prompt-selector-row:has\(\.aa-prompt-selector-favorite\.is-active\) \.aa-prompt-selector-copy \{ padding-right: 62px; \}/);
	assert.match(theme, /\.aa-prompt-selector-row\.is-selected:hover \.aa-prompt-selector-copy/);
	assert.match(theme, /\.aa-prompt-selector-weight \{[^}]*cursor: ns-resize;/);
	assert.match(theme, /\.aa-prompt-selector-summary\.is-active/);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\)/);
	assert.match(uiStyles, /\.aa-image-preview-selectable \.aa-image-preview-selection\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--aa-ui-accent\) 18%, transparent\)/s);
	assert.match(uiStyles, /\.aa-image-preview-selectable \.aa-image-preview-selection > \.aa-ui-icon\s*\{[^}]*border:\s*0;[^}]*background:\s*transparent;[^}]*color:\s*var\(--aa-ui-on-media\);[^}]*stroke-width:\s*2\.5/s);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\) \.aa-image-preview-media > img\s*\{[^}]*filter:\s*saturate\(\.92\) brightness\(\.9\)/s);
	assert.match(theme, /\.aa-prompt-entry-details-tooltip/);
	assert.match(theme, /\.aa-prompt-selection-tooltip/);
	assert.match(theme, /\.aa-prompt-selection-summary > ol/);
	assert.match(uiStyles, /\.aa-ui-tooltip\s*\{[^}]*pointer-events:\s*none/s);
	assert.doesNotMatch(theme.match(/\.aa-image-preview-tooltip\s*\{[^}]*\}/s)?.[0] || "", /pointer-events/);
	assert.doesNotMatch(theme.match(/\.aa-prompt-entry-details-tooltip\s*\{[^}]*\}/s)?.[0] || "", /pointer-events/);
	assert.doesNotMatch(promptEntryDetails, /aa-prompt-entry-details-tooltip[^\n]*interactive:\s*true/);
	assert.match(theme, /\.aa-prompt-entry-details-prompt > p, \.aa-prompt-entry-details-note > p\s*\{[^}]*white-space:\s*pre-wrap/s);
});

test("PromptSelector uses the spacious reference size as its default and resize floor", () => {
	assert.match(selector, /const DEFAULT_SIZE = \[440, 560\]/);
	assert.match(selector, /const MIN_WIDTH = 440/);
	assert.match(selector, /const MIN_HEIGHT = 560/);
	assert.match(selector, /const MIN_WIDGET_HEIGHT = 240/);
	assert.match(selector, /getMinHeight: \(\) => MIN_WIDGET_HEIGHT/);
	assert.match(selector, /if \(!loaded\) node\.setSize\?\.\(DEFAULT_SIZE\)/);
	assert.match(selector, /Math\.max\(MIN_WIDTH, size\[0\]\)/);
	assert.match(selector, /Math\.max\(MIN_HEIGHT, size\[1\]\)/);
	assert.match(theme, /\.lg-node:has\(\.aa-prompt-selector\):not\(\[data-collapsed\]\) > \[data-testid="node-inner-wrapper"\] \{[^}]*min-width: 440px;[^}]*min-height: 590px;/);
	assert.doesNotMatch(theme, /\.lg-node:has\(\.aa-prompt-selector\):not\(\[data-collapsed\]\) \{[^}]*min-width:/);
});

test("filter dropdowns reuse the shared animated select control", () => {
	assert.match(ui, /export function selectControl/);
	assert.match(ui, /aria-expanded/);
	assert.match(ui, /icon\("moveDown"/);
	assert.match(ui, /Object\.defineProperty\(root, "value", \{\s*get: \(\) => control\.value/);
	assert.match(selector, /promptFilterSelect/);
	assert.match(selector, /selectControl\(\{/);
	assert.match(workspace, /className: "aa-library-filter-select"/);
	assert.match(uiStyles, /\.aa-ui-select\.is-open \.aa-ui-select__arrow/);
	assert.match(uiStyles, /padding-right: 38px/);
	assert.match(ui, /syncOptionColor/);
	assert.match(ui, /--aa-ui-select-option-color/);
	assert.match(categoryColor, /export function categorySelectOption/);
	assert.match(selector, /value: option\.id, color: option\.color/);
	assert.match(workspace, /categories\.map\(categorySelectOption\)/);
});

test("workspace empty states and compact action bars keep narrow sidebars deliberate", () => {
	assert.match(workspace, /aa-dashboard-toolbar/);
	assert.match(workspace, /aa-library-toolbar/);
	assert.match(workspace, /iconName: "upload", label: t\("aaalice\.workspace\.preset\.export"/);
	assert.match(workspace, /iconName: "download", label: t\("aaalice\.workspace\.preset\.import"/);
	assert.match(workspace, /iconName: "upload", label: selected\.size[\s\S]*libraryUi\.export/);
	assert.match(workspace, /iconName: "download", label: t\("aaalice\.workspace\.libraryUi\.import"/);
	assert.match(workspace, /aa-workspace-empty aa-dashboard-empty/);
	assert.match(workspace, /className: "aa-dashboard-page-empty"/);
	assert.match(workspace, /aa-workspace-empty aa-library-empty/);
	assert.match(theme, /\.aa-workspace-empty\[hidden\] \{ display: none; \}/);
	assert.match(theme, /\.aa-dashboard-page-empty \{[^}]*position: absolute;[^}]*inset: 0;[^}]*place-content: center;[^}]*text-align: center;/);
	assert.match(theme, /\.aa-library-filters \{ display: grid; grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/);
});

test("dashboard page heading is prominent, responsive, and directly renameable", () => {
	assert.match(workspace, /createDashboardPageHeading\(\{[\s\S]*?page,[\s\S]*?pages: model\.pages,[\s\S]*?index: activePageIndex,[\s\S]*?onRename: renamePage,[\s\S]*?onSelectPage: selectPage,[\s\S]*?onReorderPage: reorderPage/);
	assert.match(components, /export function createDashboardPageHeading/);
	assert.match(components, /className: "aa-dashboard-page-heading__title"/);
	assert.match(components, /title\.addEventListener\("dblclick"/);
	assert.match(components, /\["Enter", "F2"\]\.includes\(event\.key\)/);
	assert.doesNotMatch(components, /aa-dashboard-page-heading__edit/);
	assert.doesNotMatch(components, /aa-dashboard-page-heading__tone/);
	assert.match(components, /inlineRename\(title,[\s\S]*?onRename\?\.\(name\)/);
	assert.match(components, /aa-dashboard-page-heading__folio-index/);
	assert.match(components, /aa-dashboard-page-heading__folio-total/);
	assert.match(components, /aa-dashboard-page-heading__folio-arrow/);
	assert.doesNotMatch(components, /folio\.addEventListener\("pointerenter"/);
	assert.doesNotMatch(components, /folio\.addEventListener\("pointerleave"/);
	assert.doesNotMatch(components, /scheduleOpen|scheduleClose|openPageMenu\(\{ focusOnOpen: false \}\)/);
	assert.doesNotMatch(components, /popover\.root\.addEventListener\("pointerenter"/);
	assert.doesNotMatch(components, /popover\.root\.addEventListener\("pointerleave"/);
	assert.match(components, /folio\.addEventListener\("click", \(\) => \{ if \(popover\) popover\.close\(\); else openPageMenu\(\); \}\)/);
	assert.match(uiSource, /focusOnOpen = true/);
	assert.match(uiSource, /if \(focusOnOpen\) \(focusableElements\(root\)\[0\] \|\| root\)\.focus\(\)/);
	assert.match(components, /onSelectPage\?\.\(entry\.id\)/);
	assert.match(components, /onReorderPage\?\.\(source, row\.dataset\.pageId\)/);
	assert.match(theme, /\.aa-dashboard-page-heading__folio \{[^}]*cursor: pointer;/);
	assert.match(theme, /\.aa-dashboard-page-heading__folio\[aria-expanded="true"\]/);
	assert.match(theme, /\.aa-dashboard-page-heading \{[^}]*min-height: 36px;[^}]*flex: 1 1 auto;/);
	assert.match(theme, /\.aa-dashboard-page-heading__title \{[^}]*font-size: 16px;[^}]*font-weight: 720;[^}]*text-overflow: ellipsis;/);
	assert.match(theme, /\.aa-dashboard-page-heading__folio \{[^}]*align-items: baseline;[^}]*font-variant-numeric: tabular-nums;/);
	assert.doesNotMatch(theme, /\.aa-dashboard-page-heading__folio \{[^}]*surface-raised/);
	assert.match(theme, /\.aa-dashboard-page-heading__folio-index \{[^}]*font-size: 13px;/);
	assert.match(theme, /\.aa-dashboard-page-heading__folio-total \{[^}]*font-size: 10px;/);
	assert.match(theme, /\.aa-dashboard-toolbar__row--actions \{[^}]*min-height: 38px;[^}]*grid-template-columns: minmax\(max-content, 1fr\) minmax\(max-content, 1fr\);/);
	assert.match(workspace, /grid\.addEventListener\("contextmenu", openBlankPageMenu\)/);
	assert.match(workspace, /event\.target\.closest\?\.\("\[data-dashboard-item-id\], \[data-dashboard-group-id\]/);
	assert.match(workspace, /event\.key !== "ContextMenu" && !\(event\.shiftKey && event\.key === "F10"\)/);
	assert.match(workspace, /label: t\("aaalice\.workspace\.page\.rename"/);
	assert.match(workspace, /className: "aa-dashboard-page-settings"/);
	assert.match(workspace, /const presetSlot = el\(\"div\", \{ className: \"aa-dashboard-toolbar__preset-slot\"/);
	assert.match(workspace, /children: \[pageHeading, presetSlot, pageSettingsButton\]\.filter\(Boolean\)/);
	assert.match(workspace, /label: t\("aaalice\.workspace\.page\.duplicate"/);
	assert.match(workspace, /label: t\("aaalice\.workspace\.page\.tone"/);
	assert.match(workspace, /\[null, \.\.\.DASHBOARD_TONES\.filter\(\(tone\) => tone !== "neutral"\)\]\.map/);
	assert.match(workspace, /label: t\("aaalice\.workspace\.layout\.separator"/);
	assert.match(workspace, /label: t\("aaalice\.workspace\.layout\.compact"/);
	assert.match(workspace, /label: t\("aaalice\.workspace\.page\.delete"/);
	assert.match(uiSource, /role", checkable \? "menuitemradio" : "menuitem"/);
	assert.match(uiSource, /action\.setAttribute\("aria-checked", String\(item\.checked\)\)/);
	assert.match(dashboardComponents, /root\.dataset\.pageTone = pageTone/);
	assert.match(workspace, /DASHBOARD_TONES\.map\(\(value\) => \[value, t\(`aaalice\.workspace\.group\.tones\./);
	assert.match(theme, /\.aa-dashboard-grid-v2\[data-page-tone\] \.aa-dashboard-group \{ --aa-dashboard-group-tone: var\(--aa-dashboard-page-tone\); \}/);
	assert.doesNotMatch(theme, /\.aa-dashboard-grid-v2\[data-page-tone\] \.aa-control-card \{ --aa-control-kind-tone:/);
	assert.match(theme, /\.aa-dashboard-grid-v2\[data-page-tone="purple"\] \{ --aa-dashboard-page-tone: var\(--p-purple-400/);
	assert.match(theme, /\.aa-dashboard-page-tone-menu-item\.is-default::before \{[^}]*dashed/);
	assert.match(themeLibrary, /@media \(max-width: 520px\) \{[\s\S]*?\.aa-dashboard-toolbar__row--context \.aa-dashboard-page-heading \{[^}]*flex-basis: auto;/);
});

test("parameter cards expose shared dashboard tone editing and persist their color", () => {
	assert.match(workspace, /label: t\("aaalice\.workspace\.card\.colorMenu", "Set card color…"\)/);
	assert.match(workspace, /createDashboardToneControl\(item\.tone\)/);
	assert.match(workspace, /openPageToneEditor/);
	assert.match(workspace, /customTone/);
	assert.match(workspace, /delete target\.tone/);
	assert.match(dashboardModel, /const itemTone = kind === "control" \? normalizeDashboardTone\(sourceItem\.tone\) : null/);
	assert.match(components, /const cardTone = normalizeDashboardTone\(item\.tone\)/);
	assert.match(components, /"data-dashboard-item-tone": hasCardTone \? cardTone : null/);
	assert.match(theme, /\.aa-control-card\.has-dashboard-tone \{/);
	assert.match(theme, /--aa-dashboard-control-tone/);
	assert.match(enLocale, /"color": "Card color", "colorMenu": "Set card color…"/);
	assert.match(zhLocale, /"color": "卡片颜色", "colorMenu": "设置卡片颜色…"/);
});

test("detached context menus retain theme tokens and visible hover feedback", () => {
	assert.match(uiStyles, /\.aa-ui-popover,\s*\n\.aa-ui-context-menu,\s*\n\.aa-ui-tooltip/);
	assert.match(ui, /ownerElement: explicitOwnerElement = null/);
	assert.match(ui, /explicitOwnerElement instanceof Element/);
	assert.match(workspace, /ownerElement: host/);
	assert.match(workspace, /ownerElement: event\.currentTarget/);
	assert.match(uiStyles, /\.aa-ui-context-menu__item\.aa-ui-button:hover:not\(:disabled\)[^}]*border-color: transparent;[^}]*background: color-mix\(in srgb, var\(--aa-ui-accent\) 14%, var\(--aa-ui-control\)\)[^}]*box-shadow: none/);
});

test("layout editing exposes an extensible component picker", () => {
	assert.match(workspace, /className: "aa-dashboard-add-page"/);
	assert.match(workspace, /createDashboardComponentPicker\(/);
	assert.match(workspace, /const dashboardComponentOptions = \[/);
	assert.match(workspace, /id: "separator", iconName: "subtract"/);
	assert.match(workspace, /className: "aa-dashboard-tidy-layout"/);
	assert.doesNotMatch(workspace, /className: "aa-dashboard-add-separator"/);
	assert.doesNotMatch(workspace, /className: "aa-dashboard-page-menu"/);
	assert.match(workspace, /grid\.addEventListener\("contextmenu", openBlankPageMenu\)/);
	assert.match(workspace, /editMode \? \[[\s\S]*aa-dashboard-add-page[\s\S]*\] : \[\]/);
	assert.match(workspace, /const layoutActions = editMode && page \? \[[\s\S]*dashboardComponentPicker\.root[\s\S]*selectAllLayoutButton[\s\S]*aa-dashboard-tidy-layout/);
	assert.match(workspace, /const selectAllLayoutButton = page && editMode \? iconButton/);
	assert.match(workspace, /aa-dashboard-toolbar__action-group--layout/);
	assert.doesNotMatch(workspace, /if \(editMode\) container\.append\(createWorkspaceToolbar/);
	assert.match(components, /export function createDashboardComponentPicker\(/);
	assert.match(components, /options\.filter\(\(option\) => option && option\.id && option\.label\)/);
	assert.match(components, /action\.dataset\.componentId = option\.id/);
	assert.doesNotMatch(components, /aa-dashboard-page-add|onAdd/);
	assert.doesNotMatch(theme, /aa-dashboard-page-add/);
	assert.doesNotMatch(theme, /aa-dashboard-add-separator/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-toolbar__action-group--primary > \.aa-ui-button, \.is-layout-editing \.aa-dashboard-toolbar__action-group--layout \.aa-ui-button \{[^}]*height: 29px;[^}]*min-height: 29px;[^}]*border-radius: 7px;/);
	assert.match(theme, /\.aa-dashboard-add-component\.aa-ui-button \{[^}]*width: 29px;[^}]*min-width: 29px;[^}]*height: 29px;/);
	assert.match(workspace, /showLabel: false/);
	assert.match(theme, /\.aa-dashboard-toolbar__action-group--utility, \.aa-dashboard-toolbar__action-group--layout \{ justify-self: end; \}/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-toolbar__action-group--layout \.aa-dashboard-add-component, \.is-layout-editing \.aa-dashboard-toolbar__action-group--layout \.aa-dashboard-select-all, \.is-layout-editing \.aa-dashboard-toolbar__action-group--layout \.aa-dashboard-tidy-layout/);
	assert.match(theme, /\.aa-dashboard-group-header h3 \{[^}]*width: fit-content;[^}]*max-width: min\(220px, 100%\);[^}]*flex: 0 1 auto;/);
	assert.match(theme, /\.aa-dashboard-component-option\.aa-ui-button:hover:not\(:disabled\)/);
});

test("workspace scrolling closes transient surfaces until motion settles", () => {
	assert.match(components, /bindScrollInteractionGuard\(root\)/);
	assert.match(uiSource, /SCROLL_INTERACTION_ATTRIBUTE = "data-aa-scroll-active"/);
	assert.match(uiSource, /root\.addEventListener\("wheel", onWheel, \{ capture: true, passive: true \}\)/);
	assert.match(uiSource, /root\.addEventListener\("scroll", begin, \{ capture: true, passive: true \}\)/);
	assert.match(uiSource, /activeTooltip\?\.isAnchoredWithin\?\.\(root\)/);
	assert.match(uiSource, /closeTransientHoverSurfacesWithin\(root\)/);
	assert.match(uiSource, /if \(isScrollInteractionActive\(nextAnchor\)\) return;/);
	assert.match(uiSource, /isAnchoredWithin: \(container\)/);
	assert.match(components, /transientHover: true/);
	assert.doesNotMatch(components, /悬停展开/);
	assert.doesNotMatch(uiSource, /preventDefault\(\).*SCROLL_INTERACTION/s);
});

test("Dashboard V4 replaces mandatory sections with optional grid groups", () => {
	assert.match(workspace, /createGroup\(current, page\.id/);
	assert.match(providers, /const widgetProvider = \(id, promoted\)/);
	assert.match(providers, /sourceSnapshot\(source, nodes\)/);
	assert.doesNotMatch(providers, /separator: \{ label: displayName\(section\.separator, section\.separator\.id\) \}/);
	assert.doesNotMatch(workspace, /function sharedSourceGroup\(controls\)/);
	assert.match(workspace, /addItems\(current, page\.id, chosen\)/);
	assert.match(workspace, /className: "aa-add-controls-source-group"/);
	assert.match(workspace, /attrs: \{ role: "heading", "aria-level": "4" \}/);
	assert.match(theme, /\.aa-add-controls-source-group \{[^}]*grid-column: 1 \/ -1;/);
	assert.match(dashboardCommands, /function findSourceGroup/);
	assert.match(dashboardCommands, /control\.sourceGroup \|\| sourceGroup/);
	assert.match(dashboardCommands, /allowSingle: true/);
	assert.doesNotMatch(dashboardCommands, /addSourceSeparator|requestedGroup\.separator/);
	assert.match(dashboardModel, /showTitle: sourceGroup\.showTitle !== false/);
	assert.match(dashboardModel, /showTitle: true, widthMode: "auto"/);
	assert.match(dashboardComponents, /export function createDashboardGroup/);
	assert.match(dashboardComponents, /const showHeader = editMode \|\| group\.showTitle !== false \|\| Boolean\(group\.source && group\.syncStatus\)/);
	assert.match(workspace, /toggleSwitch\(\{ checked: showTitle/);
	assert.match(workspace, /target\.showTitle = showTitle/);
	assert.match(enLocale, /"showTitle": "Show group title"/);
	assert.match(zhLocale, /"showTitle": "显示组标题"/);
	assert.match(dashboardComponents, /projectGroupScope\(members, groupColumns, showHeader, sizeProjections\)/);
	assert.doesNotMatch(dashboardLayout, /projectControlFootprints/);
	assert.match(dashboardLayout, /projectGroupScope/);
	assert.match(dashboardLayout, /projectWithoutOverlap/);
	assert.doesNotMatch(workspace, /projectHeaderOnlyControlFootprints/);
	assert.doesNotMatch(dashboardSizing, /projectedGroupRowSpan/);
	assert.match(dashboardComponents, /aa-dashboard-composite-card/);
	assert.match(dashboardComponents, /classList\.add\("is-group-member"\)/);
	assert.match(dashboardComponents, /dataset\.dashboardGroupMember/);
	assert.match(dashboardComponents, /data-dashboard-group-id/);
	assert.match(dashboardComponents, /page\.items\.filter\(\(item\) => !item\.groupId\)/);
	assert.match(dashboardLayout, /export function firstAvailableLayout/);
	assert.match(dashboardCommands, /export function deleteGroup/);
	assert.doesNotMatch(workspace, /createSection|findSection|lastSectionId|\.sections/);
	assert.doesNotMatch(components, /createSectionCard/);
	assert.doesNotMatch(theme, /aa-dashboard-section/);
	assert.match(theme, /\.aa-dashboard-group \.aa-control-card\.is-group-member:not\(\.has-dashboard-tone\) \{[^}]*border:\s*1px solid transparent;[^}]*background:\s*color-mix/);
	assert.match(theme, /\.aa-dashboard-group \.aa-control-card\.is-group-member:not\(\.has-dashboard-tone\):hover/);
	assert.match(theme, /\.aa-control-card\.has-dashboard-tone \{[^}]*--aa-dashboard-control-tone/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-group \.aa-control-card\.is-group-member:is\(\.is-selected, \.is-drop-target\)/);
	assert.match(theme, /\.is-layout-editing \[data-dashboard-item-id\]\.is-selected::after \{[^}]*border:\s*2px solid var\(--aa-ui-accent\);[^}]*pointer-events:\s*none;/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-separator\.is-selected::after \{ border-radius:\s*7px; \}/);
});
